# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  # Visual Studio Version
  MSVS_VERSION: 2013
  # Test against these versions of Node.js and io.js
  matrix:
    # node.js
    - nodejs_version: "0.8"
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    # io.js
    - nodejs_version: "2.5"
    - nodejs_version: "3.2"

platform:
  - x86
  - x64

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm -v
  - npm -g get prefix
  - set PATH=%APPVEYOR_BUILD_FOLDER%\node_modules\.bin;%APPDATA%\npm;%PATH%
  - echo "%PATH%"
  # Node 0.8 comes with a too obsolete npm
  - IF "%nodejs_version%" == "0.8" (npm -g install npm@1.4.28)
  - npm -v
  - npm -g get prefix
  # Install latest NPM only for node.js versions until built in node-gyp adds io.js support
  # Update is required for node.js 0.8 because built in npm(node-gyp) does not know VS2013
  - IF "%nodejs_version%" LSS "1" (npm -g install npm@2)
  - npm -v
  - npm -g get prefix
  # Typical npm stuff.
  - npm install --msvs_version=%MSVS_VERSION%

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
